# Generated by Django 3.2.8 on 2021-11-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Loyiha', 'verbose_name_plural': 'Loyihalar'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image/'),
        ),
    ]
